config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :garages, except: [:destroy, :update, :edit] do
    resources :cars, except: [:destroy, :update, :edit] do
      resources :invoices, except: [:destroy, :update, :edit, :new, :create]
      resources :contracts, except: [:destroy, :update, :edit, :new, :create]
      resources :trips, except: [:destroy, :update, :edit, :new, :create]
    end
  end

  resources :garages, only: [:destroy, :update, :edit]
  resources :cars, only: [:destroy, :update, :edit]
  resources :invoices, only: [:destroy, :update, :edit, :new, :create]
  resources :contracts, only: [:destroy, :update, :edit, :new, :create]
  resources :trips, only: [:destroy, :update, :edit, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :car
  belongs_to :trip, optional: true

  validates :price, numericality: true
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  # FACTURES = ['Entretien', 'Lavage', 'Carburant', 'Péage', 'Mécanique', 'Carosserie', 'Recharge']

  def index
    @car = Car.find(params[:car_id])
    @invoices = Invoice.where(car: @car)
  end

  def show
    @invoice = Invoice.find(params[:id])
  end

  def new
    @invoice = Invoice.new
    @car = Car.find(params[:format]) unless params[:format].nil?
  end

  def create
    @invoice = Invoice.new(invoice_params)
    if @invoice.save
      redirect_to garage_car_invoice_path(@invoice.car, @invoice.car.garage, @invoice)
    else
      render :new
    end
  end

  def edit
    @invoice = Invoice.find(params[:id])
  end

  def update
    @invoice = Invoice.find(params[:id])
    if @invoice.update(invoice_params)
      redirect_to garage_car_invoice_path(@invoice.car, @invoice.car.garage, @invoice)
    else
      render :edit
    end
  end

  def destroy
    @invoice = Invoice.find(params[:id])
    @car = @invoice.car
    @invoice.destroy
    redirect_to garage_car_invoices_path(@invoice.car.garage, @invoice.car)
  end

  private

  def invoice_params
    params.require(:invoice).permit(:name, :supplier, :piece, :price, :kilometers, :date, :car_id, :trip_id)
  end

end

app/views/invoices/edit.html.erb
<h1>Modifier <%= @invoice.name %></h1>

<%= simple_form_for(@invoice) do |f| %>
  <% if @car.nil? %>
    <%= f.association :car %>
  <% else %>
    <%= f.input :car_id, as: :hidden, input_html: { value: params[:format] } %>
  <% end %>
  <%= f.input :name %>
  <%= f.input :piece, collection: ['Entretien', 'Nettoyage', 'Carburant', 'Recharge', 'Péage', 'Mécanique', 'Carosserie', 'Amendes', 'Administratif']  %>
  <%= f.input :supplier, placeholder: 'Euromaster, Speedy etc.' %>
  <%= f.input :price, as: :float  %>
  <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"}%>
  <%= f.input :kilometers, as: :integer %>
  <%= f.submit %>

<% end %>

app/views/invoices/index.html.erb
<h1>Index invoices</h1>
<ol>
  <% @invoices.each do |invoice| %>
    <%= link_to garage_car_invoice_path(@car.garage, @car, invoice) do %>
      <li><button><%= invoice.name %> <%= invoice.piece %></button></li>
    <% end %>
  <% end %>

</ol>

<%= link_to new_invoice_path(@car) do %>
  <button>Créer une nouvelle facture</button>
<% end %>

<%= link_to garage_car_path(@car.garage, @car) do %>
  <button>Retour à la voiture</button>
<% end %>

app/views/invoices/new.html.erb
<h1>new invoice</h1>

<%= simple_form_for(@invoice) do |f| %>
  <% if @car.nil? %>
    <%= f.association :car %>
  <% else %>
    <%= f.input :car_id, as: :hidden, input_html: { value: params[:format] } %>
  <% end %>
  <%= f.input :name %>
  <%= f.input :piece, collection: ['Entretien', 'Nettoyage', 'Carburant', 'Recharge', 'Péage', 'Mécanique', 'Carosserie', 'Amendes', 'Administratif'], placeholder: 'Pneus, freins, vidange'  %>
  <%= f.input :supplier, placeholder: 'Euromaster, Speedy etc.' %>
  <%= f.input :price, as: :float  %>
  <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.input :kilometers, as: :integer %>
  <%= f.submit %>

<% end %>

app/views/invoices/show.html.erb
<h1>Show invoice</h1>

<ul>
  <li><%= @invoice.name %></li>
  <li><%= @invoice.date %></li>
  <li><%= @invoice.supplier %></li>
  <li><%= @invoice.piece %></li>
  <li><%= number_to_currency(@invoice.price, locale: :fr) %></li>
  <li><%= @invoice.kilometers %> kms</li>
  <li><%= @invoice.trip %></li>
</ul>


<%= link_to edit_invoice_path(@invoice) do %>
  <button>Modifier</button>
<% end %>

<%= link_to invoice_path(@invoice), method: :delete do %>
  <button>Supprimer</button>
<% end %>

<%= link_to garage_car_invoices_path(@invoice.car.garage, @invoice.car) do %>
  <button>Retour aux factures</button>
<% end %>