config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :garages, except: [:destroy, :update, :edit] do
    resources :cars, except: [:destroy, :update, :edit] do
      resources :invoices, except: [:destroy, :update, :edit, :new, :create]
      resources :contracts, except: [:destroy, :update, :edit, :new, :create]
      resources :trips, except: [:destroy, :update, :edit, :new, :create]
    end
  end

  resources :garages, only: [:destroy, :update, :edit]
  resources :cars, only: [:destroy, :update, :edit]
  resources :invoices, only: [:destroy, :update, :edit, :new, :create]
  resources :contracts, only: [:destroy, :update, :edit, :new, :create]
  resources :trips, only: [:destroy, :update, :edit, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/garage.rb
class Garage < ApplicationRecord
  belongs_to :user
  has_many :cars
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController

  def index
    @garages = Garage.all
  end

  def show
    find
    @cars = Car.where(garage: @garage)
  end

  def new
    @garage = Garage.new
  end

  def create
    @garage = Garage.new(garage_params)
    if @garage.save
      redirect_to garage_path(@garage)
    else
      render :new
    end
  end

  def edit
    find
  end

  def update
    find
    if @garage.update(garage_params)
      redirect_to garage_path(@garage)
    else
      render :edit
    end
  end

  def destroy
    find
    @garage.destroy
    redirect_to garages_path
  end

  private

  def garage_params
    params.require(:garage).permit(:name)
  end

  def find
    @garage = Garage.find(params[:id])
  end
end

app/views/garages/edit.html.erb
<h1>Update <%= @garage.name %></h1>

<%= simple_form_for(@garage) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/garages/index.html.erb
<div class="garage-container">
  <% if current_user.garages.count > 1 %>
    <h1>Vos <%= 'garage'.pluralize(current_user.garages) %> <%= current_user.email %></h1>
  <% else %>
    <h1>Votre <%= 'garage'.pluralize(current_user.garages) %> <%= current_user.email %></h1>
  <% end %>
  <div class="cards-garage-container">
    <% @garages.each do |garage|%>
      <%= link_to garage_path(garage) do %>
        <div class="cards-garage">
          <i class="fa-solid fa-warehouse"></i>
            <h3><%= garage.name %></h3>
            <% if garage.cars.count > 0 %>
              <h6><%= garage.cars.count %> <%= 'véhicule'.pluralize(garage.cars.count) %> </h6>
            <% else %>
              <h6>Votre garage est vide</h6>
              <%= link_to new_garage_car_path(garage) do %>
                <button class='button'>Ajouter une voiture</button>
              <% end %>
            <% end %>
            <div class="small-icon">
              <% garage.cars.each do |car| %>
                <div class="small-cards">
                  <i class="fa-solid fa-car"></i>
                  <p><%= car.model %></p>
                </div>
              <% end %>
            </div>
            <div class="icons">
              <%= link_to edit_garage_path(garage) do %>
                <i class="fa-solid fa-pencil" id="small-icon"></i>
              <% end %>
              <%= link_to garage_path(garage), method: :delete do %>
                <i class="fa-solid fa-trash-can" id="small-icon"></i>
              <% end %>
            </div>
        </div>
      <% end %>
    <% end %>
    <%= link_to new_garage_path do %>
      <div class="cards-garage">
        <i class="fa-solid fa-plus"></i>
        <h3>Créer un nouveau garage</h3>
      </div>
    <% end %>
  </div>
</div>

app/views/garages/new.html.erb
<h1>Créer un nouveau garage</h1>

<%= simple_form_for(@garage) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/garages/show.html.erb
<div class="garage-container">
  <h1>Bienvenue dans votre garage <%= @garage.name %></h1>
  <% if @garage.cars.count > 0 %>
    <h3><%= @garage.cars.count %> <%= 'véhicule'.pluralize(@garage.cars.count) %> </h3>
  <% else %>
    <h3>Votre garage est vide</h3>
  <% end %>
  <div class="retour-garage">
    <%= link_to garages_path do %>
      <button class='button'>Retour aux garages</button>
    <% end %>
  </div>

<div class="cards-garage-container">
  <% @cars.each do |car| %>
    <%= link_to garage_car_path(car.garage, car) do %>
      <div class="cards-garage">
        <i class="fa-solid fa-car"></i>
        <h3><%= car.model%></h3>
        <h6><%= number_with_delimiter(car.kilometers, delimiter: " ") %> kms</h6>
        <h6><%= number_to_currency(((Invoice.where(car: car).sum(:price)+car.purchased_price)/car.kilometers), locale: :fr) %> / km</h6>
      </div>
    <% end %>
  <% end %>
  <%= link_to new_garage_car_path(@garage) do %>
    <div class="cards-garage">
      <i class="fa-solid fa-plus"></i>
      <h3>Ajouter une voiture</h3>
    </div>
  <% end %>
</div>


</div>