config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :garages, except: [:destroy, :update, :edit] do
    resources :cars, except: [:destroy, :update, :edit] do
      resources :invoices, except: [:destroy, :update, :edit, :new, :create]
      resources :contracts, except: [:destroy, :update, :edit, :new, :create]
      resources :trips, except: [:destroy, :update, :edit, :new, :create]
    end
  end

  resources :garages, only: [:destroy, :update, :edit]
  resources :cars, only: [:destroy, :update, :edit]
  resources :invoices, only: [:destroy, :update, :edit, :new, :create]
  resources :contracts, only: [:destroy, :update, :edit, :new, :create]
  resources :trips, only: [:destroy, :update, :edit, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
  validates :name, :brand, :model, presence: true
  validates :kilometers, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :purchased_price, numericality: true
  validates :purchased_date, presence: true

  belongs_to :garage
  has_many :invoices
  has_many :contracts
  has_many :trips

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  require 'date'
  include ActionView::Helpers::DateHelper

  def index
    @cars = Car.all
  end

  def show
    find
    @garage = Garage.find(params[:garage_id])
  end

  def new
    @car = Car.new
    @garage = Garage.find(params[:garage_id])
  end

  def create
    @car = Car.new(car_params)
    @car.garage = Garage.find(params[:garage_id])

    if @car.save
      redirect_to garage_car_path(@car.garage, @car)
    else
      render :new
    end
  end

  def edit
    find
  end

  def update
    find
    if @car.update(car_params)
      redirect_to garage_car_path(@car.garage, @car)
    else
      render :edit
    end
  end

  def destroy
    find
    @garage = @car.garage
    @car.destroy
    redirect_to garage_path(@garage)
  end

############# Methode de Temps ###############
  def ownership_time(car)
    distance_of_time_in_words(Date.current, car.purchased_date)
  end
  helper_method :ownership_time

  def car_ownership(car)
    result = (car.purchased_date - Date.today).abs / 365
    result.to_i / 1
  end
  helper_method :car_ownership

  def distance_of_time_in(unit, from, to)
    diff = to - from

    if 1.respond_to? unit
      distance = diff / 1.send(unit)
      distance.abs.round
    else
      raise ArgumentError, "#{unit.inspect} is not supported as unit"
    end
  end
  helper_method :distance_of_time_in
##################################################

  def ownership_cost(car)
    (Invoice.where(car: car, piece: 'Entretien').sum(:price) + car.purchased_price)
  end
  helper_method :ownership_cost

  private

  def car_params
    params.require(:car).permit(:name, :brand, :model, :kilometers, :purchased_date, :purchased_price)
  end

  def find
    @car = Car.find(params[:id])
  end

end

app/views/cars/edit.html.erb
<h1>Modifier une voiture</h1>

<%= simple_form_for(@car) do |f| %>
  <%= f.input :name %>
  <%= f.input :brand %>
  <%= f.input :model %>
  <%= f.input :kilometers %>
  <%= f.input :purchased_price %>
  <%= f.input :purchased_date %>
  <%= f.submit %>

<% end %>

app/views/cars/new.html.erb
<h1>Ajouter une voiture</h1>

<%= simple_form_for([@garage, @car]) do |f| %>
  <%= f.input :name %>
  <%= f.input :brand %>
  <%= f.input :model %>
  <%= f.input :kilometers %>
  <%= f.input :purchased_price %>
  <%= f.input :purchased_date %>
  <%= f.submit %>

<% end %>

app/views/cars/show.html.erb
<div class="garage-container">
  <div class="title_car">
    <h1>Show de <%= @car.name %></h1>
    <%= link_to edit_car_path(@car) do %>
      <i class="fa-solid fa-pencil"></i>
    <% end %>

    <%= link_to car_path(@car), method: :delete do %>
      <i class="fa-solid fa-trash-can"></i>
    <% end %>
  </div>
  <div class="car_info_card">
    <h3>Marque: <%= @car.brand %></h3>
    <h3>Modèle: <%= @car.model %></h3>
    <h3>Acheté le <%= @car.purchased_date %></h3>
    <h3>Achetée: <%= number_to_currency(@car.purchased_price, locale: :fr, precision: 0) %> </h3>
    <h3><i class="fa-solid fa-road"></i> <%= number_with_delimiter(@car.kilometers, delimiter: " ") %> <%= 'kilomètre'.pluralize(@car.kilometers) %></h3>
  </div>
  <h3><i class="fa-solid fa-oil-can"></i></i> Coût entretien total: <%= number_to_currency(Invoice.where(car: @car).sum(:price), locale: :fr, precision: 0)%></h3>
  <h3><i class="fa-solid fa-file-invoice-dollar"></i> Coût  total: <%= number_to_currency(ownership_cost(@car), locale: :fr, precision: 0) %></h3>
  <h3>Prix au km: <%= number_to_currency((ownership_cost(@car)/@car.kilometers), locale: :fr) %> / km</h3>
  <h3>Prix par année <%= number_to_currency(ownership_cost(@car)/ car_ownership(@car), locale: :fr) %></h3>
  <h3><i class="fa-solid fa-calendar-days"></i> <%= ownership_time(@car) %></h3>

  <div class="invoice-cards">
    <div class="invoice-card">
      <%= link_to garage_car_invoices_path(@car.garage, @car) do %>
        <i class="fa-solid fa-receipt"></i>
        <h6><%= @car.invoices.count %> <%= 'facture'.pluralize(@car.invoices.count) %></h6>
        <%= link_to new_invoice_path(@car) do %>
          <button class='button'>Ajouter facture</button>
        <% end %>
      <% end %>
    </div>

    <%= link_to garage_car_contracts_path(@car.garage, @car) do %>
      <div class="invoice-card">
        <i class="fa-solid fa-file-invoice-dollar"></i>
        <h6><%= @car.contracts.count %> <%= 'contrat'.pluralize(@car.contracts.count) %></h6>
        <%= link_to new_contract_path(@car) do %>
          <button class='button'>Ajouter contrat</button>
        <% end %>
      </div>
    <% end %>

    <%= link_to garage_car_trips_path(@car.garage, @car) do %>
      <div class="invoice-card">
        <i class="fa-solid fa-route"></i>
        <h6><%= @car.trips.count %> <%= 'trajet'.pluralize(@car.trips.count) %></h6>
          <%= link_to new_trip_path(@car) do %>
            <button class='button'>Ajouter trajet</button>
          <% end %>
      </div>
    <% end %>

  </div>
  <%= link_to garage_path(@garage) do %>
    <button class='button'>Retour aux garages</button>
  <% end %>
</div>